
# arena
hall_of_glory_tabl_png = 'img/default/arena/overall/hall_of_glory_tabl.png'
hall_of_glory_icon_png = 'img/default/arena/overall/hall_of_glory_icon.png'
choice_of_the_attacked_png = 'img/default/arena/overall/choice_of_the_attacked.png'
scroll_up_png = 'img/default/arena/overall/scroll_up.png'
scroll_down_png = 'img/default/arena/overall/scroll_down.png'
attack_arena_opponent_png = 'img/default/arena/overall/attack_arena_opponent.png'

# person 'default'
gady_id = 'img/default/person/hero_id/gady/her_gady.png'
gavr_id = 'img/default/person/hero_id/gavr/her_gavr.png'
gavr_arm = 'img/default/person/hero_id/gavr/gavr_armor.png'
mara_id = 'img/default/person/hero_id/mara/her_mara.png'

# kv
p1_png = 'img/default/kv/result_round/loot/p1.png'
p2_png = 'img/default/kv/result_round/loot/p2.png'
p3_png = 'img/default/kv/result_round/loot/p3.png'
p4_png = 'img/default/kv/result_round/loot/p4.png'
p5_png = 'img/default/kv/result_round/loot/p5.png'

kv_close_png = 'img/default/kv/kv_close.png'
exit_kv_png = 'img/default/kv/exit_kv.png'
kv_skip_battle_png = 'img/default/kv/kv_skip_battle.png'
kv_skip_battle_test_png = 'img/default/kv/kv_skip_battle_test.png'
kv_danger_png = 'img/default/kv/kv_danger.png'
victory_battle_in_kv_png = 'img/default/kv/victory_battle_in_kv.png'
defeat_battle_in_kv_png = 'img/default/kv/defeat_battle_in_kv.png'
kv_reload_png = 'img/default/kv/kv_reload.png'
kv_attack_for_money_png = 'img/default/kv/kv_attack for money.png'
kv_attak_png = 'img/default/kv/kv_attak.png'

# overall
skip_battle_png = 'img/default/overall/skip_battle.png'
b_exit_png = 'img/default/overall/b_exit.png'
close_png = 'img/default/overall/close.png'
klan_png = 'img/default/overall/klan.png'
knob_png = 'img/default/overall/knob.png'
cansel_png = 'img/default/overall/cancel.png'
setting_png = 'img/default/overall/setting.png'
info_png = 'img/default/overall/info.png'
my_game2_png = 'img/default/overall/my_game2.png'
button_expand_png = 'img/default/overall/button_expand.png'

# main item
pulya_png = 'img/default/overall/pulya.png'
en1_png = 'img/default/overall/en1v3.png'
en2_png = 'img/default/overall/en2v3.png'
en3_png = 'img/default/overall/en3v3.png'

# station_master
station_master_png = 'img/default/station_master/any/station_master.png'
work_b_png = 'img/default/station_master/any/work_b.png'

# tents_R
b_vip_png = 'img/default/tents_R/b_vip.png'
inspect_tent_png = 'img/default/tents_R/inspect tent.png'
b_tent_png = 'img/default/tents_R/b_tent.png'

# tonelli
station_exit_png = 'img/default/tonelli/station_exit.png'
tonelli_attack_png = 'img/default/tonelli/attack.png'
# tonelli/map_item
k_Prospekt_png = 'img/default/tonelli/map_item/k_Prospekt.png'
k_Pr_kt_Vernadskogo_png = 'img/default/tonelli/map_item/k_Pr-kt_Vernadskogo.png'
k_Polyanka_png = 'img/default/tonelli/map_item/k_Polyanka.png'
k_Pushkin_png = 'img/default/tonelli/map_item/k_Pushkin.png'
k_Rizgskaya_png = 'img/default/tonelli/map_item/k_Rizgskaya.png'
k_Suxarev_png = 'img/default/tonelli/map_item/k_Suxarev.png'
k_Teatr_png = 'img/default/tonelli/map_item/k_Teatr.png'
k_Tretyakov_png = 'img/default/tonelli/map_item/k_Tretyakov.png'
k_Turgenev_png = 'img/default/tonelli/map_item/k_Turgenev.png'
k_Tver_png = 'img/default/tonelli/map_item/k_Tver.png'
k_Univer_png = 'img/default/tonelli/map_item/k_Univer.png'
k_VDNX_png = 'img/default/tonelli/map_item/k_VDNX.png'
k_Alexs_png = 'img/default/tonelli/map_item/k_Alexs.png'
k_Biblioteka_png = 'img/default/tonelli/map_item/k_Biblioteka.png'
k_Borov_png = 'img/default/tonelli/map_item/k_Borov.png'
k_Chekhov_png = 'img/default/tonelli/map_item/k_Chekhov.png'
k_Communist_png = 'img/default/tonelli/map_item/k_Communist.png'
k_Sport_png = 'img/default/tonelli/map_item/k_Sport.png'
k_Cvetnoy_png = 'img/default/tonelli/map_item/k_Cvetnoy.png'
k_Frunze_png = 'img/default/tonelli/map_item/k_Frunze.png'
k_Kiev_png = 'img/default/tonelli/map_item/k_Kiev.png'
k_Kiev_a_png = 'img/default/tonelli/map_item/k_Kiev_a.png'
k_Kitay_png = 'img/default/tonelli/map_item/k_Kitay.png'
k_Kropotkin_png = 'img/default/tonelli/map_item/k_Kropotkin.png'
k_Kuzneckiy_png = 'img/default/tonelli/map_item/k_Kuzneckiy.png'
k_Novokuznec_png = 'img/default/tonelli/map_item/k_Novokuznec.png'
k_Park_ganza_png = 'img/default/tonelli/map_item/k_Park_ganza.png'
k_Park_kr_png = 'img/default/tonelli/map_item/k_Park_kr.png'
k_Pavelec_png = 'img/default/tonelli/map_item/k_Pavelec.png'
k_Pavelec_g_png = 'img/default/tonelli/map_item/k_Pavelec_g.png'

# tonelli/id_stations
s_Prospekt_png = 'img/default/tonelli/id_stations/s_Prospekt.png'
s_Pr_kt_Vernadskogo_png = 'img/default/tonelli/id_stations/s_Pr-kt_Vernadskogo.png'
s_Polyanka_png = 'img/default/tonelli/id_stations/s_Polyanka.png'
s_Pushkin_png = 'img/default/tonelli/id_stations/s_Pushkin.png'
s_Rizgskaya_png = 'img/default/tonelli/id_stations/s_Rizgskaya.png'
s_Suxarev_png = 'img/default/tonelli/id_stations/s_Suxarev.png'
s_Teatr_png = 'img/default/tonelli/id_stations/s_Teatr.png'
s_Tretyakov_png = 'img/default/tonelli/id_stations/s_Tretyakov.png'
s_Turgenev_png = 'img/default/tonelli/id_stations/s_Turgenev.png'
s_Tver_png = 'img/default/tonelli/id_stations/s_Tver.png'
s_Univer_png = 'img/default/tonelli/id_stations/s_Univer.png'
s_VDNX_png = 'img/default/tonelli/id_stations/s_VDNX.png'
s_Alexs_png = 'img/default/tonelli/id_stations/s_Alexs.png'
s_Biblioteka_png = 'img/default/tonelli/id_stations/s_Biblioteka.png'
s_Borov_png = 'img/default/tonelli/id_stations/s_Borov.png'
s_Chekhov_png = 'img/default/tonelli/id_stations/s_Chekhov.png'
s_Communist_png = 'img/default/tonelli/id_stations/s_Communist.png'
s_Sport_png = 'img/default/tonelli/id_stations/s_Sport.png'
s_Cvetnoy_png = 'img/default/tonelli/id_stations/s_Cvetnoy.png'
s_Frunze_png = 'img/default/tonelli/id_stations/s_Frunze.png'
s_Kiev_png = 'img/default/tonelli/id_stations/s_Kiev.png'
s_Kiev_a_png = 'img/default/tonelli/id_stations/s_Kiev_a.png'
s_Kitay_png = 'img/default/tonelli/id_stations/s_Kitay.png'
s_Kropotkin_png = 'img/default/tonelli/id_stations/s_Kropotkin.png'
s_Kuzneckiy_png = 'img/default/tonelli/id_stations/s_Kuzneckiy.png'
s_Novokuznec_png = 'img/default/tonelli/id_stations/s_Novokuznec.png'
s_Park_ganza_png = 'img/default/tonelli/id_stations/s_Park_ganza.png'
s_Park_kr_png = 'img/default/tonelli/id_stations/s_Park_kr.png'
s_Pavelec_png = 'img/default/tonelli/id_stations/s_Pavelec.png'
s_Pavelec_g_png = 'img/default/tonelli/id_stations/s_Pavelec_g.png'